config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games

  resources :users do
    resource :parole, only:[:show, :update]
    resources :comments, only:[:index, :create, :update, :destroy]
    resources :bucket_items, only:[:index, :create, :destroy]
  end

  get 'tags/:tag', to: 'games#index', as: :tag
  root to: 'games#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_create :set_average_ratio
  after_destroy :set_average_ratio

  belongs_to :user
  belongs_to :game
  validates :rating, presence: true, inclusion: 1..5
  validates :game_id, uniqueness: { scope: :user_id }

  def set_average_ratio
    game = self.game
    ratings = game.comments.pluck(:rating)
    game_rating = ratings.count > 0 ? ratings.reduce(:+) / ratings.count : 0
    game.update(average_rating: game_rating)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ProfileLayoutController
  before_action :find_user
  COMMENTS_PER_PAGE = 10

  def index
    @q = @user.comments.ransack(params[:q])
    @pagy, @comments = pagy(@q.result, items: COMMENTS_PER_PAGE)
  end

  def create
    @comment = Comment.new(comment_params)
    flash[:error] = "#{@comment.errors.full_messages.first}" unless @comment.save
    redirect_to game_path(comment_params[:game_id]) 
  end

  def update
    @comment = @user.comments.find_by(game_id: comment_params[:game_id])
    if @comment.update(comment_params)
      redirect_to game_path(comment_params[:game_id])
    else
      redirect_to game_path(comment_params[:game_id])
    end
  end

  def destroy
    @comment = @user.comments.find_by(game_id: comment_params[:game_id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit([:rating, :content, :user_id, :game_id])
  end
end

app/views/comments/index.html.haml
.row.game-comments-name
  %h1 Comments
- @comments.each do |c|
  .row.game-comments.align-items-center
    .col-2
      = link_to c.game.name, game_path(c.game)
    .col-3
      - c.rating.to_i.times do
        %span.fa.fa-star.checked
      - (5 - c.rating.to_i).times do
        %span.fa.fa-star
    .col-5.comment-body
      = c.content
    .col-2
      = form_with scope: :comment, local: true, url: user_comment_path(current_user, c.game), method: :delete do |f|
        = f.hidden_field(:user_id, value: current_user.id)
        = f.hidden_field(:game_id, value: c.game.id)
        %button.btn.fas.fa-trash.btn-primary{type: "submit"}
.row.justify-content-center.mt-5
  != pagy_bootstrap_nav(@pagy) if @pagy.pages > 1