config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games

  resources :users do
    resource :parole, only:[:show, :update]
    resources :comments, only:[:index, :create, :update, :destroy]
    resources :bucket_items, only:[:index, :create, :destroy]
  end

  get 'tags/:tag', to: 'games#index', as: :tag
  root to: 'games#index'
end

app/models/game.rb
class Game < ApplicationRecord

  has_one_attached :cover
  has_many_attached :screenshots
  has_many :comments
  has_many :users, through: :comments
  has_many :taggings
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings, allow_destroy: true
  validates :name, presence: true, length: { maximum: 128 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true, length: { maximum: 500 }
  ransacker :price_money, formatter: proc { |dollars| dollars.to_i * 100 } do |p|
    p.table[:price]
  end

  def self.tagged_with(name)
    if name.present?
      Tag.find_by_name!(name).games
    else
      Game.all
    end
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  ITEMS_PER_PAGE = 12
  COMMENTS_PER_PAGE = 10

  def index
    @q = Game.tagged_with(params[:tag]).ransack(params[:q])
    @pagy, @games = pagy(@q.result, items: ITEMS_PER_PAGE)
  end

  def show
    @game = Game.includes(:comments, :users).find(params[:id])
    @q = @game.comments.ransack(params[:q])
    @pagy, @comments = pagy(@q.result, items: COMMENTS_PER_PAGE)
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def to_dollars(price)
    "$#{price/100.to_f}"
  end

  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
  end
  
  def tag_cloud(tags, classes)
    max = 0
    tags.each do |t|
      if t.count.to_i > max
        max = t.count.to_i
      end 
    end
    tags.each do |tag|
      index = tag.count.to_f / max * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/games/index.html.haml
.wrapper.d-flex
  .sidebar-wrapper.bg-primary.border-right.row.justify-content-center
    = search_form_for @q do |f|
      .search
        = f.search_field(:name_cont, placeholder: 'Search games', class: 'form-control')
        .row.justify-content-between
          .col-6
            = f.search_field(:price_money_gteq, placeholder: 'Min Price', class: 'form-control')
          .col-6
            = f.search_field(:price_money_lteq, placeholder: 'Max Price', class: 'form-control')  
        = f.submit(placeholder: "search", class: 'form-control')
      = sort_link(@q, :average_rating) do
        %strong Rating
  .page-content-wrapper 
    .container-fluid
      #tag_cloud
        - tag_cloud Game.tag_counts, %w[xxs xs s m l xl xxl] do |tag, css_class|
          = link_to tag.name, tag_path(tag.name), class: css_class
      .row.justify-content-center 
        - @games.each do |game|
          .card.game-card
            = link_to image_tag(game.cover, size: '300x200'), game_path(game) if game.cover.attached?
            .card-body
              %h5.card-title= truncate(game.name, length: 20)
              - game.average_rating.to_i.times do
                %span.fa.fa-star.checked
              - (5 -game.average_rating.to_i).times do
                %span.fa.fa-star
              %p.card-text.mt-1= to_dollars(game.price)
      .row.justify-content-center
        != pagy_bootstrap_nav(@pagy) if @pagy.pages > 1

app/views/games/show.html.haml
.row.game-page
  .col-6
    .game_slider
      - @game.screenshots.each_with_index do |ss, index|
        %div{class: "game-slide"}
          = image_tag(ss, :class => 'img-fluid')
    .nav_game_slider
      - @game.screenshots.each_with_index do |ss, index|
        %div{class: "game-slide"}
          %div{class:"game-slide__wrapper"}
            = image_tag(ss, :class => 'img-fluid')
  .col-6
    %p.game_name
      = @game.name
    %p.game_data
      %strong= Game.human_attribute_name("price:")
      = to_dollars(@game.price)
    %p
      - @game.average_rating.to_i.times do
        %span.fa.fa-star.checked
      - (5 -@game.average_rating.to_i).times do
        %span.fa.fa-star
    %p.game_data
      %strong= Game.human_attribute_name("tags:")
      = raw tag_links(@game.tag_list)
    %p.game_data
      %strong= Game.human_attribute_name("description:")
      = @game.description
    - if user_signed_in?
      - if current_user.games.include?(@game)
        %h3 Added to your Bucket
        = form_with scope: :bucket_item, local: true, url: user_bucket_item_path(current_user), method: :delete do |f|
          = f.hidden_field(:user_id, value: current_user.id)
          = f.hidden_field(:game_id, value: @game.id)
          = f.submit('Remove from Bucket', class: 'btn btn-primary btn-lg') 
      - else
        = form_with scope: :bucket_item, local: true, url: user_bucket_items_path(current_user), method: :post do |f|
          = f.hidden_field(:user_id, value: current_user.id)
          = f.hidden_field(:game_id, value: @game.id)
          = f.submit('Add to Bucket', class: 'btn btn-primary btn-lg')
    
.row.game-page
  .col-6.comment
    - if user_signed_in?
      = form_with scope: :comment, local: true, url: user_comments_path(current_user), method: :post do |f|
        = f.hidden_field(:user_id, value: current_user.id)
        = f.hidden_field(:game_id, value: @game.id)
        .row
          .col-6
            = f.text_area(:content, placeholder: 'Leave a comment...', class: 'form-control', cols: 1, rows: 3)
          .col-6
            .row.flex-column.justify-content-between.comment_raiting
              .row
                %h5.mr-2 rating
                = f.select(:rating, options_for_select([1, 2, 3, 4, 5]))
              = f.submit('Save', class: 'btn btn-primary')
.row.game-comments-name
  %h1 Comments
- @comments.each do |c|
  .row.game-page.align-items-center
    .col-2
      = image_tag(c.user.avatar, size: '50x50') if c.user.avatar.attached?
      = c.user.nickname
    .col-2
      - c.rating.to_i.times do
        %span.fa.fa-star.checked
      - (5 - c.rating.to_i).times do
        %span.fa.fa-star
    .col-6.comment-body
      = c.content
.row.justify-content-center.mt-5
  != pagy_bootstrap_nav(@pagy) if @pagy.pages > 1