config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games

  resources :users do
    resource :parole, only:[:show, :update]
    resources :comments, only:[:index, :create, :update, :destroy]
    resources :bucket_items, only:[:index, :create, :destroy]
  end

  get 'tags/:tag', to: 'games#index', as: :tag
  root to: 'games#index'
end

app/controllers/paroles_controller.rb
# frozen_string_literal: true

class ParolesController < ProfileLayoutController
  before_action :find_user

  def show
  end

  def update
    unless @user.valid_password?(params[:user][:old_parole])
      flash.now[:alert] = "Error: current password invalid"
      render 'show'
      return
    end

    if @user.update(password_params)
      sign_in(@user)
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "Error: #{@user.errors.full_messages.join(', ')}"
      render 'show'
    end
  end

  private
  
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/views/paroles/show.html.haml
%h2 Change your password
= form_with scope: :user, local: true, url: user_parole_path, method: :patch do |f|
  .field
    = f.label :old_parole, 'Old password'
    %br/
    = f.password_field :old_parole, autofocus: true, class: 'form-control'
  .field
    = f.label :password, 'New password'
    %br/
    = f.password_field :password, autofocus: true, class: 'form-control'
  .field
    = f.label :password_confirmation, 'Confirm new password'
    %br/
    = f.password_field :password_confirmation, class: 'form-control'
  .actions
    %br/
    = f.submit('Change my password', class: 'btn btn-primary')